# Configurations given in order of: data, correlations, MCMC
# Dictionaries are functions of flux cut

LoTSS_DR2:
  lss_survey_name: LoTSS_DR2
  is_optical: False
  # mask_coverage, mask_default, mask_noise_75percent, mask_noise_99_percent, mask_noise_median, mask_optical
  lss_mask_name: mask_coverage
  nside: 512
  flux_min_cut: 2
  signal_to_noise: 5

  dn_dz_model: 'power_law'  # 'deep_fields', 'z_tail', 'power_law'
  # Old redshift distribution
  z_tail: {2: 1.3, 1: 1.0, 0.5: 1.0}
  # New redshift distribution
  # First line: Dominik's fits
#  z_sfg: {2: 0.13, 1: 0.14, 0.5: 0.15}
  z_sfg: {2: 0.15, 1: 0.22, 0.5: 0.15}
#  a: {2: 4.66, 1: 4.60, 0.5: 4.56}
  a: {2: 4.8, 1: 5.2, 0.5: 4.56}
#  r: {2: 0.94, 1: 0.90, 0.5: 0.93}
  r: {2: 0.91, 1: 0.80, 0.5: 0.93}
  # Bias
  bias_model: 'scaled'  # 'linear', 'scaled', 'polynomial'
  b_0_scaled: {2: 1.5, 1: 1.2, 0.5: 1.1}
  b_0: {2: 1, 1: 0, 0.5: 0}
  b_1: {2: 1, 1: 0, 0.5: 0}
  b_2: {2: 1, 1: 0, 0.5: 0}

  read_data_correlations_flag: False
  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  l_range: {
    gg: [102, 802],
    gk: [102, 802],
#    gg: [2, 120],
#    gt: [2, 120],
  }
  ells_per_bin: {
    gg: 50,
    gk: 50,
#    gg: 16,
#    gt: 16,
  }

  continue_sampling: False
  starting_params: {b_0_scaled: [1.4, 0.5]}  # , sigma8: [0.83, 0.1]}
  max_iterations: 5000
  n_walkers: 32


LoTSS_DR1:
  lss_survey_name: LoTSS_DR1
  is_optical: True
  nside: 512
  flux_min_cut: 2
  signal_to_noise: 5

  dn_dz_model: 'deep_fields'  # 'deep_fields', 'z_tail', 'power_law'
  # Old redshift distribution
  z_tail: {2: 2.0}
  bias_model: 'scaled'  # 'linear', 'scaled', 'polynomial'
  b_0_scaled: {2: 1.4}  # 2.1

  read_data_correlations_flag: False
  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  l_range: {
    gg: [2, 502],
#    gk: [2, 502],
  }
  ells_per_bin: {
    gg: 50,
#    gk: 50,
  }

  continue_sampling: False
  starting_params: {b_0_scaled: [1.4, 0.5]}  # , sigma8: [0.83, 0.1]}
  max_iterations: 5000
  n_walkers: 32


KiDS_QSO:
  lss_survey_name: KiDS_QSO
  nside: 512
  bias: 1.6
  scale_bias: True

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gk]
  l_max: {
    gg: 510,
    gk: 510,
  }
  ells_per_bin: {
    gg: 50,
    gk: 50
  }

  continue_sampling: False
  max_iterations: 5000
  starting_params: {bias: [2.1, 0.5], sigma8: [0.83, 0.1]}
  n_walkers: 32


NVSS:
  lss_survey_name: NVSS
  nside: 512
  bias: 2.18
  scale_bias: False

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gt]
  l_min: {
    gg: 10,
    gt: 4,
  }
  ell_lengths: {
    gg: [8, 14, 26],
    gt: [6, 12, 24, 52],
  }

  continue_sampling: False
  max_iterations: 5000
  starting_params: {bias: (2.18, 0.5)}
  n_walkers: 32
