# Configurations given in order of: data, correlations, MCMC
# Dictionaries are functions of flux cut

LoTSS_DR2:
  lss_survey_name: LoTSS_DR2
  is_optical: False
  lss_mask_name: mask_inner
  # mask_coverage, mask_default, mask_noise_75percent, mask_noise_99_percent, mask_noise_median, mask_optical, mask_inner
  nside: 512
  flux_min_cut: 1.5
  signal_to_noise: 7.5

  read_correlations_flag: False
  read_covariance_flag: True
  error_method: jackknife  # jackknife, gauss
  l_range: {
#    gg: [102, 1602],
#    gk: [52, 1752],
    gg: [102, 752],
    gk: [52, 802],
#    gg: [2, 120],
#    gt: [2, 120],
  }
  ells_per_bin: {
    gg: 50,
    gk: 50,
#    gg: 16,
#    gt: 16,
  }

  dn_dz_model: 'power_law'  # 'deep_fields', 'z_tail', 'power_law', 'tomographer'
  z_tail: {2: 1.3, 1.5: 0, 1: 1.0, 0.5: 1.0}
  # Lines: Dominik's fit to deep fields; my fit to tomographer; my fit to tomographer * D(z)
  z_sfg: {2: 0.13, 1.5: 0.13, 1: 0.14, 0.5: 0.15}
#  z_sfg: {2: 0.039, 1.5: 0.039}
#  z_sfg: {2: 0.038, 1.5: 0.037}
  a: {2: 4.66, 1.5: 6.64, 1: 4.60, 0.5: 4.56}
#  a: {2: 3.59, 1.5: 3.33}
#  a: {2: 4.45, 1.5: 4.20}
  r: {2: 0.94, 1.5: 0.92, 1: 0.90, 0.5: 0.93}
#  r: {2: 0.18, 1.5: 0.18}
#  r: {2: 0.18, 1.5: 0.19}
  n: {2: 1, 1.5: 1}
#  n: {2: 1, 1.5: 109298}
#  n: {2: 0, 1.5: 111252}

  # Bias
  bias_model: 'constant'
  # constant
  b_g: {2: 3.0, 1.5: 3.0}
  # scaled
  b_g_scaled: {2: 1.4, 1.5: 1.3, 1: 1.2, 0.5: 1.1}
  # polynomial
  b_0: {2: 1.4, 1.5: 1.3}
  b_1: {2: 1, 1.5: 0}
  b_2: {2: 1, 1.5: 0}
  # tomographer
  b_eff: {2: 2.9, 1.5: 2.7}

  # Shot noise
  A_sn: {2: 1, 1.5: 1}

  # Cosmology
  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit

  # Inference
  continue_sampling: False
  redshift_to_fit: deep_fields  # tomographer, deep_fields, None
  to_infere: [sigma8, b_g, A_sn, z_sfg, a, r]
  max_iterations: 100000
  n_walkers: 32


LoTSS_DR1:
  lss_survey_name: LoTSS_DR1
  is_optical: True
  nside: 512
  flux_min_cut: 2
  signal_to_noise: 5

  dn_dz_model: 'z_tail'  # 'deep_fields', 'z_tail', 'power_law'
  # Old redshift distribution
  z_tail: {2: 0.9}
  bias_model: 'scaled'  # 'linear', 'scaled', 'polynomial'
  b_0_scaled: {2: 1.4}  # 2.1 from DR1, 1.4 for deep fields

  read_data_correlations_flag: False
  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  l_range: {
    gg: [2, 502],
    gk: [2, 502],
  }
  ells_per_bin: {
    gg: 50,
    gk: 50,
  }

  continue_sampling: True
  starting_params: {b_0_scaled: [1.5, 1.0], z_tail: [1.5, 1.0]}  # , sigma8: [0.83, 0.1]}
  max_iterations: 5000
  n_walkers: 32


KiDS_QSO:
  lss_survey_name: KiDS_QSO
  nside: 512
  bias: 1.6
  scale_bias: True

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gk]
  l_max: {
    gg: 510,
    gk: 510,
  }
  ells_per_bin: {
    gg: 50,
    gk: 50
  }

  continue_sampling: False
  max_iterations: 5000
  starting_params: {bias: [2.1, 0.5], sigma8: [0.83, 0.1]}
  n_walkers: 32


NVSS:
  lss_survey_name: NVSS
  nside: 512
  bias: 2.18
  scale_bias: False

  cosmology_name: planck
  cosmology_matter_power_spectrum: halofit
  correlation_symbols: [gg, gt]
  l_min: {
    gg: 10,
    gt: 4,
  }
  ell_lengths: {
    gg: [8, 14, 26],
    gt: [6, 12, 24, 52],
  }

  continue_sampling: False
  max_iterations: 5000
  starting_params: {bias: (2.18, 0.5)}
  n_walkers: 32
